### ISSUE TITLE
probando luz y sonido

### ISSUE THREAD

**Issue by allansmac** [Jorghe/Modbus-GUI#1]
No pude abrir nada, abri cada uno pero los codigo no e relacionan con la aplicacion.

**Comment by Jorghe** [comment]
Checa si después del commit [8701c2b](https://github.com/Jorghe/Modbus-GUI/commit/8701c2b522fe3e23d8d86ea5b539a9e83d9e399c)  puedes abrirlo.

**Comment by allansmac** [comment]
No se como abrir el 8701c3b. puedo ver el codigo en esta plataforma pero no lo puedo bajar para abrirlo en el visual.

**Comment by allansmac** [comment]
ya pude abrirlo, se ve bien pero hay un bug por ahi, porque tengo tengo dos archivos de modsim, que cuando le doy el coil 1 aparece conectado pero dura un segundo y me mando un error en el codigo, (imagen 1) por lo que vi esta buscando por el valor de algun register, entonces le doy un valor x al register y me manda al error de red limit (imagen2) 
[Error 1 y 2.docx](https://github.com/Jorghe/Modbus-GUI/files/2064577/Error.1.y.2.docx)

**Comment by Jorghe** [comment]
El **bug** se generaba al tratar de accesar a la llave de un diccionario que no estaba definido.
El bug ya se solucionó, estaremos usando un nuevo formato para que te sea más fácil el proceso de reporte de "issues":
* Una **descripción** general del error o la nueva implementación
* Una descripción de cómo reproducir el error.
* Un screenshot del mensaje **Error** y la linea y documento en donde ocurrió
